[package]
name = "azul_hello"
version = "0.1.0"
authors = ["Andrei Kniazev <andrei.kniazev@yorlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azul = "0.1.0"