[package]
name = "fractals"
version = "0.1.0"
authors = ["Andrei Kniazev <andrei.kniazev@yorlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.2"
num-complex = "0.2.3"