[package]
name = "pnet_example"
version = "0.1.0"
authors = ["Andrei Kniazev <andrei.kniazev@yorlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"